/**
 * Local-nginx host config writer.
 *
 * For hosts in `mode='local_nginx'`, we write a per-host nginx conf to
 * /data/nginx/hosts/<id>.conf, validate with `nginx -t`, then reload.
 *
 * The Docker image's nginx is configured to include /data/nginx/hosts/*.conf
 * from its main config (see docker/nginx/cloudgate.conf).
 *
 * Cert acquisition (ACME via DNS-01) is handled separately by acme.ts.
 */

import { spawn } from 'node:child_process';
import { writeFile, rename, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { Liquid } from 'liquidjs';
import { dataPath } from '../config.js';
import { childLogger } from '../logger.js';

const log = childLogger('nginx-config');
const engine = new Liquid({ trimTagLeft: true, trimOutputLeft: true });

const HOST_TEMPLATE = `# Auto-generated by CloudGate — do not edit manually
# Host #{{ id }}: {{ hostname }}

upstream cloudgate_host_{{ id }} {
    server {{ forward_host }}:{{ forward_port }};
}

server {
    listen 80;
    listen [::]:80;
    server_name {{ hostname }};

    {% if cert_path -%}
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate {{ cert_path }};
    ssl_certificate_key {{ cert_key_path }};

    # HSTS — opt-in once cert is stable
    # add_header Strict-Transport-Security "max-age=31536000" always;

    # Redirect HTTP → HTTPS
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }
    {%- endif %}

    location {{ path_prefix }} {
        proxy_pass {{ forward_scheme }}://cloudgate_host_{{ id }};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        {% if no_tls_verify -%}
        proxy_ssl_verify off;
        {%- endif %}
    }
}
`;

export interface RenderHost {
	id: number;
	hostname: string;
	forward_scheme: string;
	forward_host: string;
	forward_port: number;
	path_prefix: string;
	no_tls_verify: boolean;
	cert_path?: string;
	cert_key_path?: string;
}

async function nginxTest(): Promise<{ ok: boolean; stderr: string }> {
	return new Promise((resolve) => {
		const proc = spawn('nginx', ['-t']);
		let stderr = '';
		proc.stderr.on('data', (c) => {
			stderr += c.toString();
		});
		proc.on('close', (code) => resolve({ ok: code === 0, stderr }));
		proc.on('error', (err) => resolve({ ok: false, stderr: err.message }));
	});
}

async function nginxReload(): Promise<void> {
	return new Promise((resolve, reject) => {
		const proc = spawn('nginx', ['-s', 'reload']);
		proc.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`nginx reload exit ${code}`))));
		proc.on('error', reject);
	});
}

/**
 * Render + atomic write + validate. Rolls back on failure.
 */
export async function writeHostConfig(host: RenderHost): Promise<void> {
	const outPath = dataPath('nginx', 'hosts', `${host.id}.conf`);
	const tmpPath = `${outPath}.${process.pid}.tmp`;

	// Snapshot existing (for rollback)
	let previous: string | null = null;
	if (existsSync(outPath)) {
		const fs = await import('node:fs/promises');
		previous = await fs.readFile(outPath, 'utf8');
	}

	const yaml = await engine.parseAndRender(HOST_TEMPLATE, host);
	await writeFile(tmpPath, yaml, { encoding: 'utf8', mode: 0o644 });
	await rename(tmpPath, outPath);

	const test = await nginxTest();
	if (!test.ok) {
		log.warn({ host: host.hostname, stderr: test.stderr }, 'nginx -t failed, rolling back');
		if (previous !== null) {
			await writeFile(outPath, previous, 'utf8');
		} else {
			await unlink(outPath).catch(() => null);
		}
		throw new Error(`nginx config validation failed: ${test.stderr}`);
	}

	await nginxReload().catch((err) => {
		log.warn({ err: (err as Error).message }, 'nginx reload failed — config valid but reload errored');
		throw err;
	});

	log.info({ host: host.hostname, path: outPath }, 'nginx host config deployed');
}

/**
 * Remove a host's config + reload.
 */
export async function removeHostConfig(hostId: number): Promise<void> {
	const path = dataPath('nginx', 'hosts', `${hostId}.conf`);
	if (!existsSync(path)) return;
	await unlink(path);
	await nginxReload().catch((err) => {
		log.warn({ err: (err as Error).message }, 'nginx reload after removal failed');
	});
	log.info({ hostId }, 'nginx host config removed');
}
