/**
 * Local-nginx host config writer.
 *
 * For hosts in `mode='local_nginx'`, we write a per-host nginx conf to
 * /data/nginx/hosts/<id>.conf, validate with `nginx -t`, then reload.
 *
 * The Docker image's nginx is configured to include /data/nginx/hosts/*.conf
 * from its main config (see docker/nginx/cloudgate.conf).
 *
 * Cert acquisition (ACME via DNS-01) is handled separately by acme.ts.
 */

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { rename, unlink, writeFile } from 'node:fs/promises';
import type { ForwardedHeaderMode } from '@cloudgate/shared';
import { Liquid } from 'liquidjs';
import { dataPath } from '../config.js';
import { childLogger } from '../logger.js';

const log = childLogger('nginx-config');
// NOTE: `trimOutputLeft` must stay OFF. It strips the whitespace to the left
// of every `{{ … }}`, which turned `server {{ forward_host }}` into
// `server192.168.1.50` and made every generated config fail `nginx -t` —
// i.e. local_nginx hosts could never deploy. Whitespace control is done
// explicitly with `{%-` / `-%}` markers in the template instead.
const engine = new Liquid({ trimTagLeft: true });

// IMPORTANT — this template must stay SELF-CONTAINED.
//
// The self-updater (docker/apply-update.sh) only swaps /app/{backend,
// frontend,recovery-ui}. It never replaces /etc/nginx-cloudgate/*.conf and
// never restarts nginx. A freshly-updated backend therefore writes host
// configs that are read by the OLD image-level nginx config. If this
// template referenced anything declared there (a shared `map`, a named
// upstream, a variable), `nginx -t` would fail on every self-updated
// install and host deploys would break. Hence the per-host `map` with an
// id-suffixed variable name below: it lives in the same file that uses it,
// and the suffix keeps two host files from redeclaring the same variable.
const HOST_TEMPLATE = `# Auto-generated by CloudGate — do not edit manually
# Host #{{ id }}: {{ hostname }}

# Only send "Connection: upgrade" when the client actually asked for an
# upgrade. Sending it unconditionally breaks keep-alive on every plain
# request and confuses strict origins.
map $http_upgrade $cg_conn_upgrade_{{ id }} {
    default upgrade;
    ''      close;
}

upstream cloudgate_host_{{ id }} {
    server {{ forward_host }}:{{ forward_port }};
}

server {
    listen 80;
    listen [::]:80;
    server_name {{ hostname }};
{%- if cert_path %}

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate {{ cert_path }};
    ssl_certificate_key {{ cert_key_path }};

    # HSTS — opt-in once cert is stable
    # add_header Strict-Transport-Security "max-age=31536000" always;

    # Redirect HTTP → HTTPS
    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }
    {%- endif %}

    # Cloudflare's edge and many apps send large cookies; nginx's default
    # 8k header buffer rejects those with its own 400 before the origin
    # ever sees the request.
    large_client_header_buffers 4 32k;

    # nginx defaults to a 1 MB request body. That silently breaks file
    # uploads, backup restores and media sync on the origin. 0 = defer the
    # limit to the origin, which is the one that actually knows.
    client_max_body_size 0;

    location {{ path_prefix }} {
        proxy_pass {{ forward_scheme }}://cloudgate_host_{{ id }};
        proxy_http_version 1.1;
        proxy_set_header Host {{ host_header }};
        proxy_set_header X-Real-IP $remote_addr;
        {%- if forwarded_headers == 'strip' %}
        # forwarded_headers=strip — an empty value makes nginx omit the
        # header entirely. For origins that reject proxied requests
        # outright (Home Assistant without trusted_proxies). The origin
        # sees every visitor as CloudGate, so its per-client rate limiting
        # and brute-force banning can no longer tell clients apart.
        proxy_set_header X-Forwarded-For "";
        proxy_set_header X-Forwarded-Proto "";
        proxy_set_header X-Forwarded-Host "";
        proxy_set_header CF-Connecting-IP "";
        {%- elsif forwarded_headers == 'client_ip_only' %}
        # forwarded_headers=client_ip_only — exactly one entry, so origins
        # that choke on multi-hop chains still get a usable client IP.
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        {%- else %}
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        {%- endif %}
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $cg_conn_upgrade_{{ id }};
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
{%- if no_tls_verify %}
        proxy_ssl_verify off;
{%- endif %}
    }
}
`;

export interface RenderHost {
	id: number;
	hostname: string;
	forward_scheme: string;
	forward_host: string;
	forward_port: number;
	path_prefix: string;
	no_tls_verify: boolean;
	cert_path?: string;
	cert_key_path?: string;
	/** See ForwardedHeaderMode in @cloudgate/shared. Defaults to 'standard'. */
	forwarded_headers?: ForwardedHeaderMode;
	/** Host header sent upstream. Defaults to nginx's `$host`. */
	http_host_header?: string;
}

/**
 * Values that reach the template. Everything optional in `RenderHost` is
 * resolved to a concrete value here so the template never has to guess —
 * a missing Liquid variable renders as an empty string, which in an nginx
 * directive means a config that fails `nginx -t`.
 */
interface TemplateHost extends RenderHost {
	forwarded_headers: ForwardedHeaderMode;
	host_header: string;
}

function toTemplateHost(host: RenderHost): TemplateHost {
	return {
		...host,
		forwarded_headers: host.forwarded_headers ?? 'standard',
		// An explicit override is quoted so hostnames can't be read as nginx
		// syntax; the default is the `$host` variable and must stay bare.
		host_header: host.http_host_header ? `"${sanitiseHeaderValue(host.http_host_header)}"` : '$host',
	};
}

/**
 * nginx has no escaping for directive arguments, so anything user-supplied
 * that lands in a config file has to be reduced to characters that cannot
 * terminate a directive or open a block. A bad value here would otherwise
 * be rejected by `nginx -t` at best, and inject config at worst.
 */
function sanitiseHeaderValue(value: string): string {
	return value.replace(/[^A-Za-z0-9._:\-[\]]/g, '').slice(0, 253);
}

/**
 * Render a host's nginx config without touching the filesystem.
 * Exported so tests can assert on the output (and run it through a real
 * `nginx -t`) without a /data mount or a running nginx.
 */
export async function renderHostConfig(host: RenderHost): Promise<string> {
	return engine.parseAndRender(HOST_TEMPLATE, toTemplateHost(host));
}

async function nginxTest(): Promise<{ ok: boolean; stderr: string }> {
	return new Promise((resolve) => {
		const proc = spawn('nginx', ['-t']);
		let stderr = '';
		proc.stderr.on('data', (c) => {
			stderr += c.toString();
		});
		proc.on('close', (code) => resolve({ ok: code === 0, stderr }));
		proc.on('error', (err) => resolve({ ok: false, stderr: err.message }));
	});
}

async function nginxReload(): Promise<void> {
	return new Promise((resolve, reject) => {
		const proc = spawn('nginx', ['-s', 'reload']);
		proc.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`nginx reload exit ${code}`))));
		proc.on('error', reject);
	});
}

/**
 * Render + atomic write + validate. Rolls back on failure.
 */
export async function writeHostConfig(host: RenderHost): Promise<void> {
	const outPath = dataPath('nginx', 'hosts', `${host.id}.conf`);
	const tmpPath = `${outPath}.${process.pid}.tmp`;

	// Snapshot existing (for rollback)
	let previous: string | null = null;
	if (existsSync(outPath)) {
		const fs = await import('node:fs/promises');
		previous = await fs.readFile(outPath, 'utf8');
	}

	const yaml = await renderHostConfig(host);
	await writeFile(tmpPath, yaml, { encoding: 'utf8', mode: 0o644 });
	await rename(tmpPath, outPath);

	const test = await nginxTest();
	if (!test.ok) {
		log.warn({ host: host.hostname, stderr: test.stderr }, 'nginx -t failed, rolling back');
		if (previous !== null) {
			await writeFile(outPath, previous, 'utf8');
		} else {
			await unlink(outPath).catch(() => null);
		}
		throw new Error(`nginx config validation failed: ${test.stderr}`);
	}

	await nginxReload().catch((err) => {
		log.warn({ err: (err as Error).message }, 'nginx reload failed — config valid but reload errored');
		throw err;
	});

	log.info({ host: host.hostname, path: outPath }, 'nginx host config deployed');
}

/**
 * Remove a host's config + reload.
 */
export async function removeHostConfig(hostId: number): Promise<void> {
	const path = dataPath('nginx', 'hosts', `${hostId}.conf`);
	if (!existsSync(path)) return;
	await unlink(path);
	await nginxReload().catch((err) => {
		log.warn({ err: (err as Error).message }, 'nginx reload after removal failed');
	});
	log.info({ hostId }, 'nginx host config removed');
}
